#!/bin/bash
# Blocks writes to build artifacts, binary files, and dependency directories.
# Used as a PreToolUse hook for Edit|Write operations.
# Exit 2 = block the action. Exit 0 = allow.

# Requires jq for JSON parsing. Fail closed if missing
if ! command -v jq >/dev/null 2>&1; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"jq is required for file protection hooks but is not installed.\"}}"
  exit 2
fi

INPUT=$(cat)
# notebook_path: NotebookEdit carries its target under a different key.
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // .tool_input.notebook_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Repo root, used to anchor the dependency directories that are only ever
# vendored AT the root. Prefer the harness variable; fall back to the git root
# rather than bare $(pwd) -- with an unset variable and a cwd below the root,
# a bare pwd makes the anchored arm miss and the guard FAILS OPEN on an
# absolute path to the real vendor/ directory. Trailing slash stripped so the
# arm cannot become `<root>//vendor/*` and match nothing.
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
PROJECT_DIR="${PROJECT_DIR%/}"

# Collapse `.`, `..` and duplicate slashes before matching. Without this,
# <root>/app/../vendor/x and <root>//vendor/x resolve to the protected
# directory while dodging the anchored arm -- the unanchored rule this
# replaced caught them, so normalizing is what keeps the narrowing honest.
# String-only: never touches the filesystem, so a missing path still matches.
NORMALIZED_PATH=$(printf '%s' "$FILE_PATH" | awk '
  { n = $0
    gsub(/\/+/, "/", n)
    while (n ~ /\/\.\//) sub(/\/\.\//, "/", n)
    while (n ~ /\/[^\/]+\/\.\.\//) sub(/\/[^\/]+\/\.\.\//, "/", n)
    print n }')
FILE_PATH="$NORMALIZED_PATH"

# Block dependency and build directories
case "$FILE_PATH" in
  node_modules/*|*/node_modules/*)
    REASON="Cannot write into node_modules/. Install dependencies via package manager instead." ;;
  # ANCHORED TO THE REPO ROOT, deliberately. Unlike node_modules, "vendor" is an
  # ordinary English word, and this codebase has real application paths that
  # contain it -- app/api/me/vendor/ today, and any future vendor-scoped route.
  # The previous `*/vendor/*` arm matched those and blocked every edit to them
  # for subagents AND the orchestrator, with a message about dependency managers
  # that gave no hint the block was a false positive. It cost a real fix a full
  # round trip. A vendored dependency directory (PHP Composer, Go modules) only
  # ever lives at the repo root, so anchoring there keeps the real protection
  # and drops the collision.
  "$PROJECT_DIR"/vendor/*|vendor/*|./vendor/*)
    REASON="Cannot write into the repo-root vendor/ directory. Use a dependency manager instead." ;;
  dist/*|*/dist/*|build/*|*/build/*|.next/*|*/.next/*)
    REASON="Cannot write into build output directories. These are generated by the build process." ;;
  __pycache__/*|*/__pycache__/*)
    REASON="Cannot write into __pycache__/. These are generated by Python." ;;
  .venv/*|*/.venv/*|venv/*|*/venv/*)
    REASON="Cannot write into virtual environment directories." ;;
  *)
    REASON="" ;;
esac

if [ -n "$REASON" ]; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"$REASON\"}}"
  exit 2
fi

# Block binary and archive file extensions
BASENAME=$(basename "$FILE_PATH")
case "$BASENAME" in
  *.wasm|*.so|*.dylib|*.dll|*.exe|*.o|*.a)
    REASON="Cannot write binary files. These should be compiled, not hand-written." ;;
  *.zip|*.tar|*.tar.gz|*.tar.bz2|*.tgz|*.rar|*.7z)
    REASON="Cannot write archive files." ;;
  *.mp4|*.mov|*.avi|*.mkv|*.mp3|*.wav|*.flac)
    REASON="Cannot write media files. Add these manually outside Claude Code." ;;
  *.pyc|*.pyo|*.class)
    REASON="Cannot write compiled bytecode files." ;;
esac

if [ -n "$REASON" ]; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"$REASON\"}}"
  exit 2
fi

exit 0
